spring:
  application:
    name: resort-service
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: org.h2.Driver
    username: h2
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080